services:
  backend:
    build: .
    ports:
      - '3001:3001'
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  postgres:
    image: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - psql:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  psql:
  node_modules:
